artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Alphapara97/NLP_text_summery/blob/main/summarizer-data.zip
  local_data_file: artifacts/data_injestion/data.zip
  unzip_dir: artifacts/data_ingestion
  